name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest
      
    strategy:    
      matrix:
        channel: ["stable", "beta"]
      
    steps:
     - uses: actions/checkout@v2
     - uses: subosito/flutter-action@v1
       with:
         channel: ${{ matrix.channel }}

     - run: flutter pub get
     - run: flutter test
